### PR TITLE
Solution in python of the ShoppingcartEasy problem

### PR DESCRIPTION
**Pull request by neha07kumari**
Here is the solution to the ShoppingCartEasy problem coded in python.

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please change the solution code from `.txt` to `.py` format. Also, a brief description(not more than 4-5 lines/100 words) needs to be included containing the approach used for solving the problem along with the screenshot in any format (`pdf`, `md`, `doc` etc).

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
I'm getting this error while running this python script. Can you please resolve it?

image

Also, we don't need this file `Easy/1. Shopping Cart Problem/solutions/neha07kumari_NehaKumari/~$reenshot.doc.docx`, please remove it.

**Comment by irshadjsr21** [comment]
Hello @neha07kumari,

This is to inform you that, you will not receive your badge if your PR is merged after **31st July 2020**.
Please update the requested change requests before 31st July.

Thanks & Regards!

**Comment by neha07kumari** [comment]
Respected sir

The changes have been done.

Thankyou
Neha

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please display the shopping list in a proper way with the index.
image

**Comment by neha07kumari** [comment]
> Please display the shopping list in a proper way with the index.
> image

done

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃
Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
