### PR TITLE
Added solution to Shopping cart easy

### PR DESCRIPTION
**Pull request by Vanshikaa00**
Solution for shopping cart Easy problem solved in java

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
1. We need different PR's for different levels. So please remove the `Medium` level solution from this PR and create a new one for it.

2. Also. a brief description(not more than 4-5 lines/100 words) needs to be included containing the approach used for solving the problem along with the screenshot in a pdf document format.

3. The current folder `53425575_Vanshika` is not a valid format. It should be `<Your Github ID>_<Your Name>`. As I can see, your github id is `Vanshikaa00`.

**Comment by Vanshikaa00** [comment]
Hello!! @irshadjsr21 I've added the requested changes.

**Review by irshadjsr21 — APPROVED** [review]
Great work, Although this is the first shop I know selling `Earphones`, `Bread` & `Pizza` in one place. :stuck_out_tongue:

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃
Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Comment by Vanshikaa00** [comment]
haha 😆 Also, thanks for the merge! 😃

**Pull request merged**
