### PR TITLE
Shopping cart

### PR DESCRIPTION
**Pull request by poojabh08**
Solution to level Easy Shopping cart problem

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please add a document in **.pdf** format for the following point in your folder.
- A document containing a screenshot showing the results must also be pushed along with the final submission. A brief description(not more than 4-5 lines/100 words) should be included containing the approach used for solving the problem.

Also display the respective item amounts along with the shopping items. Refer to the highlighted area in the below screenshot.

Screenshot 2020-07-06 at 11 50 01 PM

**Review by girlscript-blr — APPROVED** [review]
Extremely sorry for the delayed response.

**Comment by girlscript-blr** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) of the problem and try your hand at it to earn higher-level badges. Thanks for your contribution! Happy coding😃

**Comment by poojabh08** [comment]
Thank you so much for this opportunity.
It's really appreciated by every beginners.

**Pull request merged**
