### PR TITLE
Shopping cart medium

### PR DESCRIPTION
**Pull request by neha07kumari**

### CODE REVIEW

**Review by yati1998 — CHANGES_REQUESTED** [review]
Please send a PR to girlscript-blr:solution branch. Kindly refer to CONTRIBUTING.md file's Create Pull Request point.

Now that you have created the PR, you can click on the Edit button beside the PR title and change the branch this PR is pointing to. Please follow the below steps.

1. Click on Edit.



2. Change the base branch from master to solution.

**Comment by neha07kumari** [comment]
Changes made

**Review by yati1998 — CHANGES_REQUESTED** [review]
Please go through the proper required inputs and outputs. Things like Home delivery option is not mentioned, even the distance thing is not taken. For complete details go through this : https://github.com/neha07kumari/code-with-girlscript-bangalore/blob/ShoppingCartMedium/Medium/1.%20Shopping%20Cart%20Problem/README.md

**Comment by neha07kumari** [comment]
Maam its mentioned , there is a question which asks whether you want home delivery or takeaway and then if home delivery is selected it asks the distance . for the reference you can see the secreenshot folder.

**Comment by neha07kumari** [comment]
screenshot*

**Comment by yati1998** [comment]
Output
Output will be a bill based on the given input. The bill can be in any format but it must include the following

Static data
Shop name: GadgetifyWithGSBlr
Shop address: 311/5 Akshay nagar, Bangalore, Karnataka, India
Shop contact no: +91 9988776655
Variable data
Customer name
Customer phone no
Items bought, it's quantity, price & discount price
Total tax
Total shipping charge (if Home delivery is selected)
Total amount saved
Sum amount to be paid
Payment method used
Billing date and time
Shipping Address (if Home delivery is selected)
These are the outputs that needs to be displayed.
On selecting the home delivery option neither the shipping address nor shipping charge is displayed

**Comment by yati1998** [comment]
Screenshot from 2020-07-31 11-58-50
Uploading the screenshot for your understanding. Please check once again on this.

**Comment by neha07kumari** [comment]
Ma'am I'm not getting you. It's written shipping charges and address would
be show only if only home delivery is selected and so does my output
show(the one you showed me) .
Do I need to show shipping charges and address(even if home delivery is not
selected) then also and write there home delivery not selected .

**Review by yati1998 — APPROVED** [review]

**Comment by yati1998** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `MEDIUM` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Medium` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out our [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem and try your hand at it to earn **THE AFICIONADO** 🥇 and **GEEK OF THE GEEKS** 🏆 badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
