### PR TITLE
Added Escapeezy easy solution

### PR DESCRIPTION
**Pull request by AnjaliPatle**

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Seems like GS-blr-Easy folder is empty, with any solution.

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Seems like the whole solution folder is missing now. Could you please verify and send.
Screenshot 2020-12-07 at 5 32 48 PM

**Comment by AnjaliPatle** [comment]
I included a react app in the solution folder, which created a submodule in my repository on pushing, due to .git files present in the app folder. Unfortunately, I'm unable to add/replace files to this repository. I'm receiving "fatal :adding files failed" error. I think I need to clone the repository again and then follow the procedure for contribution. Kindly let me know if you could help me in resolving this error, or in case I need to make a new PR.

**Comment by girlscript-blr** [comment]
Hello @AnjaliPatle,

If any .git file is created in the internal folders try deleting it. Only one .git file should exist and that should be in the main/base folder where the [main readme.md](https://github.com/girlscript-blr/code-with-girlscript-bangalore/blob/master/README.md) file is present. Try adding the react app again after deleting .git file from internal folders.

If you still face issues, you can send a new PR by forking the repo and copy-pasting your react application. Please remember to exclude the node-modules folder while copy-pasting the react js app.

Thanks

**Comment by AnjaliPatle** [comment]
Hello, I have created another pull request with the correct files as I was unable to add files on this branch. Kindly consider the new PR.
Thanks

**Comment by girlscript-blr** [comment]
Similar PR created in #140

**Pull request closed without merging**
