### PR TITLE
Dhm medium

### PR DESCRIPTION
**Pull request by srimanikantapalakollu**
Implemented the Digital Hospital Monitoring Medium Problem Solution for the Hacktoberfest Challenge.

### CODE REVIEW

**Comment by srimanikantapalakollu** [comment]
@girlscript-blr please review my PR.

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
You application look amazing 😍 

Just I found one **bug** in the app.
The `Discharge Date` can't be before the `present date`. I am sure that can be fixed in the calender.
Screenshot 2020-10-08 at 12 59 22 AM

**Comment by srimanikantapalakollu** [comment]
@girlscript-blr Implemented the requested changes. please review my PR.!

**Review by girlscript-blr — APPROVED** [review]

**Comment by girlscript-blr** [comment]
Dear participant, we have gone through your pull request made in `Intermediate` sections of the Problem Statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **Digital Hospital Manager** - Medium section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Also [RSVP here](https://tinyurl.com/gsblr-hacktoberfest2020) to win\* a limited edition **Hacktoberfest** 👕Tee-shirt or a 🎍plant if you haven't yet.

Try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
