### PR TITLE
Digital Hospital Management (Medium) Solution.

### PR DESCRIPTION
**Pull request by pallavisavant**

### CODE REVIEW

**Comment by pallavisavant** [comment]
@girlscript-blr pls do review..Thanks:)

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please resolve the following change requests:

- It seems like the `.sql file` is missing in this folder. Refer screenshot
Screenshot 2020-10-20 at 1 33 19 PM

Also similar to easy problem resolve the following:
- **Age & Weight** should accept only integers
- On click of `Submit Button` a message or something should pop up to let the user know that the data has been successfully added.
- (This is a suggestion) There should also be a **back button to navigate back** to the main page. 

Screenshot 2020-10-20 at 1 31 37 PM

- In **Update Patient Page**, it is better to have `patient id` in place of `patient name` as few patients can have same names, where as patient id will be unique entity.

Screenshot 2020-10-20 at 1 37 13 PM

**Comment by pallavisavant** [comment]
@girlscript-blr made required changes...Thank you.

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please resolve the following change requests:
- In update Patient details I am able to give a `discharged/ death date & time` before the date of admission, which is wrong. **Please disable the calendar dates before the date of admission.** 
Screenshot 2020-10-21 at 11 35 09 PM
Screenshot 2020-10-21 at 11 36 59 PM


- I am able to update Patient details for invalid PatientId. For eg. here there is no patient with `Patient Id 52`, but the app is allowing me to enter details and submit. At least after submission the alert pop up should display correct msg stating **Patient not found** or something.
Screenshot 2020-10-21 at 11 51 28 PM

 
- I am able to manually add patient details into the `phpmyadmin`, which displays in the app. I am also able to update patient details which get updated in the DB, **but when I add I a new Patient, I still don't see any records in the DB**.

**Please share some screenshots where you add a new patient and that record gets stored into the phpmyadmin SQL DB.**

**Comment by pallavisavant** [comment]
@girlscript-blr  Fixed all the suggested requirements...
included ss for reference that its updating data in phpmyadmin SQL db
Before updating the db.
Before_update

Entering details for updating.
Update_details

After updating the sql db.
After_update

Thanks.

**Review by girlscript-blr — APPROVED** [review]

**Comment by girlscript-blr** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in the `Medium` sections of the Problem Statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **Digital Hospital Manager - Medium** section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Also [RSVP here](https://tinyurl.com/gsblr-hacktoberfest2020) to win\* a limited edition **Hacktoberfest** 👕Tee-shirt or a 🎍plant if you haven't yet.

Learning is a never-ending process. 📈 Check out the [Hard](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/4.%20Digital%20Hospital%20Manager) and [Bonus](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Bonus/4.%20Digital%20Hospital%20Manager) level problem statements and try your hand at it for earning higher-level badges. 

Thanks for your contribution! 
Happy coding😃

**Pull request merged**
