### PR TITLE
Shopping Cart done

### PR DESCRIPTION
**Pull request by damini31**
It was fun solving this problem.

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Here I'm being asked to select an item but the item list haven't been displayed yet.
image

**Tip**
Whenever you create an application where the user is allowed to select an item, don't make the user type its name. Because the user might make a mistake and your app can crash. Another reason is you'll have do a search operation to find the item the user has typed. To avoid this ask the user to just enter the index of the item in that list (like 1, 2, 3, etc).

**Comment by damini31** [comment]
I have made the necessary changes.Please see to it and let me know if any more changes are required.
Thank you! :D

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Everything seems good, just a last change.

The first item is on the same line as the headings.
image

Also, update the doc with the latest output screenshot.

**Comment by damini31** [comment]
I have updated the screenshot in the document and have made the required changes in the code as well.

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃
Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
