### PR TITLE
Shop cart easy

### PR DESCRIPTION
**Pull request by SlaYpoint**
Solution to ShopCartEasy problem. Description along with screenshots given inside README.pdf file.
[README.pdf](https://github.com/girlscript-blr/code-with-girlscript-bangalore/files/4870349/README.pdf)

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please resolve the following issues in the solution folder:
- Remove the **.pyc files**. Those need not be pushed into the repo as they are just compiled python binary files.

- There is a bug in your code, I guess it is trying to create a new invoice file under bills folder but due to path mismatch it fails. Refer to the screenshot below:

Screenshot 2020-07-07 at 1 03 26 AM

- If generating the invoice by creating a file doesn't seem to work. Please display the invoice in the console itself and upload the screenshot.

- Add a brief description(not more than 4-5 lines/100 words) about your approach used for solving the problem.

**Comment by SlaYpoint** [comment]
I made the changes and committed on Jul 13 , haven't received any response
yet.

**Comment by girlscript-blr** [comment]
Hello @SlaYpoint,

Extremely sorry for the delayed response. 

Your Easy level code seems to work fine, but I can't approve the PR as it contains medium level problem files.
Please remove the medium levels files checked into this PR and share a separate PR for Medium. 
Also the document stating the approach and successful solution screenshots seems to be missing for your medium level problem. Please add them into your Medium level PR.

**Comment by SlaYpoint** [comment]
Ok. Sorry I guess that came by mistake. Im still working on the medium
level problem.
I have removed those files and commited.

**Review by girlscript-blr — APPROVED** [review]

**Comment by girlscript-blr** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) of the problem and try your hand at it for earning higher level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
