### PR TITLE
Shopping Cart problem- easy solution

### PR DESCRIPTION
**Pull request by zenit-abh**
I have uploaded the source code and the output screenshot with little introduction.

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please resolve the following change requests:
- Send PR to `girlscript-blr:solution` branch in place of `girlscript-blr:master`. This can be done by clicking on `Edit button` on the top right corner beside Open with button. Refer screenshot:
Screenshot 2020-07-08 at 12 57 27 AM

- The codes/files should be inside a single folder following a specific naming convention. The solution folder name should be `<your GitHub Id>_<your name>`.
- Root Folder
    - Problem Statement
      - Solutions
        - `<Your solution folder>`

- Please remove all the files created outside your folder and only check-in your folder containing a solution file along with readme.md and .doc file.

- Your code seems to work fine but, it will be better if you make the user select numbers in place of typing word. Chances of spelling mistakes increase when a user types the product/item name. Refer screenshot:
Screenshot 2020-07-08 at 12 51 41 AM

**Comment by zenit-abh** [comment]
I have made changes as asked by you please have a look and let me know.

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please undo the changes in file path: Easy/1. Shopping Cart Problem/solutions/README.md 
We don't want any changes to be done outside your folder.

Also send a PR to `girlscript-blr:solution` branch in place of `girlscript-blr:master`.

**Comment by zenit-abh** [comment]
I have send the PR to the girlscript-blr:solution but merging is blocked
there

**Comment by girlscript-blr** [comment]
Closing this as PR #31 was sent to commit into `girlscript-blr:solution` branch.

**Pull request closed without merging**
