### PR TITLE
added easy solution 

### PR DESCRIPTION
**Pull request by Anmolreshi**

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please correct the file extensions.
1. `README.md.txt` should be `README.md`
2. `easysolution.cpp.txt` should be `easysolution.cpp`

**Comment by ibhanu** [comment]
He closed the PR I guess!

**Comment by Anmolreshi** [comment]
okay i will make changes

**Comment by Anmolreshi** [comment]
I have made the changes kindly see to it ..

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
1. Please provide a screenshot to the output in Readme file.
2. The tax calculation is incorrect.
3. The payment method & item bought should be displayed correctly on the bill. Instead of 1, 2, 3 It should have the name of the product and name of payment method.
image

**Comment by girlscript-blr** [comment]
Hello @Anmolreshi 

This is to inform you that, we will be soon closing this PR without merging if we don't get a response by tomorrow EOD.

Thanks & Regards

**Pull request closed without merging**
