### PR TITLE
Digital hosp easy

### PR DESCRIPTION
**Pull request by AnjaliPatle**

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please resolve the following change requests:
- Mention in which format the date is to be mentioned, I added the current date as `25th Oct 2020` and the app ran in an infinite loop.
Screenshot 2020-10-25 at 4 35 36 PM

- When entering the height as `5ft 5`, **5** is being taken as symptoms. It will be better if you mention the unit on the left and accept only `integers/decimals/float` for `age, weight & height`.
Eg: 
**Enter Weight in kg: 85
Enter Height in cm: 165**
 
Screenshot 2020-10-25 at 4 33 27 PM

- A suggestion, it will be better if you provide options for **Gender** as `Male, Female, Other` & **Blood group** as `O+ve, O-ve, AB+ve, B+ve etc.` instead of asking the user to type it.

**Comment by AnjaliPatle** [comment]
Thank you for your review and such well-described suggestions. I've made the necessary changes. Kindly look into it and suggest  further improvements if needed.

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Everything works fine only the last 2 bugs to fix.
- When I select **Option 3**, I am asked for the date again, please mention in which format the date should be inputted as it is done in the beginning.
Screenshot 2020-10-25 at 7 27 56 PM

- Also if I enter any **invalid data like some random string** for `Age, Weight or Height`, the **app seems to break and go into an infinite loop**. This should be handled & User should be asked to retry with proper error message like: **Invalid Input, Please enter valid data**
Screenshot 2020-10-25 at 7 28 49 PM

**The main objective of a coder is that his/her app should never break in any scenario.**

**Comment by AnjaliPatle** [comment]
Thank you for your review. I have made the changes.

**Review by girlscript-blr — APPROVED** [review]

**Comment by girlscript-blr** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in the `Easy` sections of the Problem Statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **Digital Hospital Manager - Easy** section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Also [RSVP here](https://tinyurl.com/gsblr-hacktoberfest2020) to win\* a limited edition **Hacktoberfest** 👕Tee-shirt or a 🎍plant if you haven't yet.

Learning is a never-ending process. 📈 Check out the [Medium](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/4.%20Digital%20Hospital%20Manager) , [Hard](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/4.%20Digital%20Hospital%20Manager) and [Bonus](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Bonus/4.%20Digital%20Hospital%20Manager) level problem statements and try your hand at it for earning higher-level badges. 

Thanks for your contribution! 
Happy coding😃

**Pull request merged**
