### PR TITLE
Hard Challenge Covid-19 App

### PR DESCRIPTION
**Pull request by srimanikantapalakollu**
Implementation of Covid-19 Application.!

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please resolve the following issues in the solution.
> It will be better if we show list of slum names along with their IDs to select from or Serial number whichever is convenient. In that way, the admin user will make fewer mistakes with the spellings and don't have to remember all the slum names and then type.
Screenshot 2020-09-10 at 10 55 50 PM
Screenshot 2020-09-12 at 10 28 45 AM

> While being in Admin functionality when I select **y** to continue. It takes directly to user options, rather it should take to Admin functionality options.
Screenshot 2020-09-12 at 10 36 24 AM

> While adding special Item details, there is no option to add monthly quantity and price.
Screenshot 2020-09-12 at 10 39 08 AM

> Because of which when user tries to register a survey and selects one of the special items eg. Horlicks or Glucose. It is not found in the **fetch food info by Aadhar number** options.
Screenshot 2020-09-12 at 10 31 35 AM

**Comment by girlscript-blr** [comment]
Hello @srimani-programmer 
Please resolve the changes requested to earn your badges.

Thanks

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
I mentioned the same issue in my previous Change Request. Seeing the same again

The issue is in `Add/Update Special Item`. I am getting an option to add a Special Item, but there is no option to **add price or monthly quantity**. `Eg. here I added Chevanprash`
Screenshot 2020-10-02 at 6 59 00 PM

So now registering the survey when I add a special item in this case `Chevanprash` & `Calcium Sandoz tablets`.
Screenshot 2020-10-02 at 7 00 33 PM

But when I try to fetch the food details for a particular slum, I am not able to see the special item i.e. `Chevanprash` & `Calcium Sandoz tablets`. But they should have been present.
Screenshot 2020-10-02 at 7 03 30 PM

**Comment by srimanikantapalakollu** [comment]
A Wrong Merge happened into the Code base.

**Comment by girlscript-blr** [comment]
Hello @srimani-programmer 

I still don't see any new commits as per review comments. As this PR was submitted in mid of September, you can still merge your changes to this for receiving additional badge & securing more points. 

We will be accepting this PR, if you commit before 8th October.

Thanks.

**Pull request closed without merging**
