### PR TITLE
Implemented the Shopping Cart Easy Problem Solution.

### PR DESCRIPTION
**Pull request by srimanikantapalakollu**

### CODE REVIEW

**Review by yati1998 — COMMENTED** [review]
Please check contributing.md file for proper folder format.
"the solution folder name should be <your GitHub Id>_<your name>."  Update the PR with the required change.

**Review by yati1998 — CHANGES_REQUESTED** [review]
Please send a PR to girlscript-blr:solution branch. Kindly refer to CONTRIBUTING.md file's Create Pull Request point.

Now that you have created the PR, you can click on the Edit button beside the PR title and change the branch this PR is pointing to. Please follow the below steps.

1. Click on Edit.



2. Change the base branch from master to solution.

**Review by yati1998 — APPROVED** [review]

**Comment by yati1998** [comment]
Greetings from Code With Girlscript Bangalore😃
Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Comment by srimanikantapalakollu** [comment]
I didn't receive my badge yet. When will I receive my badge?

**Comment by yati1998** [comment]
@srimani-programmer your badge will be send to you soon till than you can take up the other levels problem.

**Pull request merged**
