### PR TITLE
Shopping cart medium

### PR DESCRIPTION
**Pull request by damini31**
The problem was interesting.

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please remove the easy solution from this PR. 
Also, the shipping charge calculations seems to be incorrect. It should be this.
image

**Comment by damini31** [comment]
I have made the required changes.
Thank you!

**Comment by irshadjsr21** [comment]
Please resolve the conflicts. If you are having any trouble in resolving the conflict, please reach out to us.

**Comment by damini31** [comment]
Hi,
Can you please help me in resolving the conflicts?

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `MEDIUM` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Medium` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out our [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem and try your hand at it to earn **THE AFICIONADO** 🥇 and **GEEK OF THE GEEKS** 🏆 badges. Thanks for your contribution! Happy coding😃

**Comment by damini31** [comment]
Thank you for helping me out! :D

**Pull request merged**
