### PR TITLE
Hard solution for IPL Management App

### PR DESCRIPTION
**Pull request by 4doctorstrange**
Refer ReadME.txt to run web-app locally

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
I just found one bug in this. Please resolve it.
- While **Updating a match, Team won** is a `text box`, because of which an admin can enter some invalid input as well, which is currently being accepted by the app. 
It is better to convert that into a `drop-down` displaying only the 2 teams playing the match. Screenshot for reference. 

Screenshot 2020-11-22 at 8 16 47 PM

**Comment by 4doctorstrange** [comment]
Thanks for letting me know about the bug. I have implemented the changes as asked, please let me know if it is working fine or any other change is required. 
enabling drop down
updated schedule(dropdown )

**Review by girlscript-blr — APPROVED** [review]

**Comment by girlscript-blr** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `HARD` sections of the problem statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **IPL Management App - Hard** section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Stay tuned for our upcoming **Problem Statements for the Month of December**.

Thanks for your contribution! 
Happy coding😃

**Comment by 4doctorstrange** [comment]
Thanks!

**Pull request merged**
