### PR TITLE
Submission of Hard/1. Shopping Cart Problem/

### PR DESCRIPTION
**Pull request by chttrjeankr**
- Application created to let user shop for multiple items from multiple categories of valid quantity with applicable discounts and 6% tax
- User is allowed to opt for home delivery for under 50 km distance from the shop
- The vendor is allowed to add categories and items for shopping, and change order statuses accordingly
- `Items`, `Categories` and `Orders` are stateful and can be retrieved after restarting the application

@irshadjsr21 @girlscript-blr

<hr>

## Improvements from last solution

> > * Display add to cart button initially and when the item is added to the cart, show the quantity change input.
> >   image
> > * Currently when you go to the shopping list page, add some item, click checkout, and click continue shopping, your selections won't be displayed on the shopping list page.
> 
>   **When user goes to the shopping list page, adds some item, clicks checkout, and clicks continue shopping, thier selections are displayed and the `Add to Cart` button changes to `Update Quantity` button**
>   image
> 
> 
> > * Currently, I can enter my name in the phone no field. This can easily be fixed with input type and pattern attribute.
> >   image
> 
>   **Handled with a `HTML` form-level validation of `type="number"`**
> 
> > * The date and time can be made more user friendly.
> >   image
> 
>   **Handled with a readable format**
>   image
> 

_Originally discussed at [this PR](https://github.com/girlscript-blr/code-with-girlscript-bangalore/pull/48#pullrequestreview-450185272)_

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
You can skip this comment. There was a glitch in my git setup and I accidentally reviewed a previous version of your code.

**Comment by chttrjeankr** [comment]
Completely fine. 👍🏻 Let me know if the current version of code is good to go. 😀

<details>
<summary>P.S.</summary>
Just adding a clarification here, if needed.
There are currently a total of 62 commits for the Hard solution which starts from 9f92fe1 and ends at e680b7a. This branch was created from the master branch and thus doesn't contain any of the other solutions, neither mine nor others'.
</details>

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
After discussing with the team we decided not to accept the django admin panel as the vendor UI. 
Please create the vendor features similar to the customer features.

**Comment by chttrjeankr** [comment]
The Django Admin is meant to be used _exactly for this purpose_ ([to let trusted users manage content on the site](https://docs.djangoproject.com/en/3.0/ref/contrib/admin/#module-django.contrib.admin)) and in this particular PR, I [customized it ](https://github.com/chttrjeankr/code-with-girlscript-bangalore/blob/shopping-cart-hard/Hard/1.%20Shopping%20Cart%20Problem/solutions/chttrjeankr_Ankur_Chattopadhyay/shoppingcart/admin.py) to an extent so that it fits perfectly to the vendor's point of view - implementing the functions of filtering and sorting and custom permissions as required. The functionality of the Django website is totally in accordance with the problem statement and the [General Guidelines](https://github.com/girlscript-blr/code-with-girlscript-bangalore#general-guidelines) of the program.

If the team still decides just not to accept it just because they don't want to, it'd be more transparent and in the spirit of OpenSource to include a reason for the decision too in the review.

I'm open to make further customisations to the admin interface and override inbuilt templates, but if the decision is to ask me to reinvent the wheel with a fully new UI and newly coded functions to handle things that are already being handled in a readable much easier way, I'd request you to go forward and _close this PR_, as I believe the change would be totally uncalled for and would be extremely redundant and unnecessary. Also, reinventing the wheel is _exactly_ what Django tries to _avoid_.

> image
> _from https://www.djangoproject.com/_
> 

**If the decision doesn't mean that, let me know what exactly bothers you with the Django admin panel and how it hinders your workflow, and I'll keep improving it to suit a vendor's needs.**

@irshadjsr21 @girlscript-blr @yati1998 @ibhanu

**Comment by irshadjsr21** [comment]
The whole purpose of "Code with girlscript Bangalore" is to allow the participants to solve a particular problem using any programming language or tool they prefer so that they can learn to build real world solutions. But this does not mean we can allow a prebuilt solution like django administrator panel. 

Allowing such solutions will mean allowing other such prebuilt or nocode tools (like WordPress or Wix etc) which is not what "Code with Girlscript Bangalore" is about.

Coming to this particular problem. Suppose you are building this platform for a production environment. And you have multiple users and vendors in using your app. Will you really give access to all the vendors to the superadmin panel of Django? You will want to restrict the roles and permissions of the vendors so that they can perform only some limited number of tasks. Also, you don't want the vendors to go to another UI to perform the vendor tasks. You have to allow them to perform those tasks in the same UI.

Consider GitHub for example. Here in this repo I have access to merge the pull requests and you don't. I don't have to go to a GitHub admin panel to merge your pull request. I can do it on the same PR page. The permissions are handled in such a way that I can see the active merge PR button and you see the disabled merge PR button.

This is not about reinventing the wheel. This is about looking into how the wheel was built, breaking down it's working and creating a custom wheel that fits the particular use case.

**Comment by chttrjeankr** [comment]
If we were to have multiple user and vendors, then yeah this would require a totally different approach. I understood the [problem statement](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem#problem-statement) referred to a single Vendor as the Admin of the site, which handles a single shop `GadgetifyWithGSBlr`:
> **‘Vendor mode’ which allows the admin** to perform various tasks like adding shopping items, viewing and filtering customer’s orders and changing the status of the orders.

I now understand what new improvements you are looking for in the Hard solution and **I'll look at how I can implement it**. I believe it'd require creating authorizations for different users and vendors, which earlier seemed out of scope for the problem statement.

**Comment by chttrjeankr** [comment]
Also, the problem statement did mention the clear separation of two modes: Customer and Vendor:
> image

Vendor mode was to be exclusive of the Customer mode and were meant to be for two different audiences altogether.

**Comment by irshadjsr21** [comment]
Yes, the customer and the vendor section are different, but they are on the same app, so the UI can't be totally different. Also, the vendor needs to have limited features as mentioned in the problem statement. 

Here the vendor is also a user, so you can't expect them to create an account on the Django CLI and then access the admin panel. It should be on the application UI so that it is easily accessible. 

The authentication is not required for this problem but you can go ahead with it if you want to. For simplicity, you can just have two buttons, one for `Customer` and another for `Vendor` on the home page which will take the user to their respective sections (simulating a login).

**Comment by chttrjeankr** [comment]
The buttons sound good. I'll try pushing new commits soon. 👍🏻

**Comment by chttrjeankr** [comment]
Just to confirm, the Vendor login is not needed to be implemented for this problem, right? Only a simulation (clicking a button to go to a new page) is needed? So, technically if a user goes to a URL meant for a vendor directly, they will be seeing the vendor page. Would that be acceptable for this problem? @irshadjsr21

**Comment by irshadjsr21** [comment]
Yes, that's correct

**Comment by chttrjeankr** [comment]
Updated Homepage:
> image

@irshadjsr21

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `Hard` sections of the problem statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the `Shopping Cart Problem - Hard` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Stay tuned for our upcoming Problem Statements for the Month of August. Thanks for your contribution! Happy coding😃

**Comment by chttrjeankr** [comment]
Thank you for the reviews of July. Looking forward to August! 🌟

**Pull request merged**
