### PR TITLE
Shopping cart easy

### PR DESCRIPTION
**Pull request by Sachindrck**
I have used python list to store the shopping item details.

### CODE REVIEW

**Comment by girlscript-blr** [comment]
- Please send a PR to **girlscript-blr:solution** branch. Kindly refer to CONTRIBUTING.md file's **Create Pull Request** point.
- Also a brief description(not more than 4-5 lines/100 words) needs to be included containing the approach used for solving the problem along with the screenshot in a pdf document format.

**Comment by Sachindrck** [comment]
Sure @girlscript-blr

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
- Please send a PR to girlscript-blr:solution branch. Kindly refer to CONTRIBUTING.md file's Create Pull Request point.
- Also a brief description(not more than 4-5 lines/100 words) needs to be included containing the approach used for solving the problem along with the screenshot in a pdf document format.

**Comment by girlscript-blr** [comment]
Hello @Sachindrck ,

This is to inform that, you will not receive your badge if your PR is merged after **31st July 2020**.
Please update the requested change requests before 31st July.

Thanks & Regards!

**Comment by girlscript-blr** [comment]
No response from Participant, hence closing this PR.

**Pull request closed without merging**
