### PR TITLE
Pacman easy

### PR DESCRIPTION
**Pull request by swetakyada**
I have created Pacman game (Easy), in which pacman can move using (w, a, s, d). '-' and '|' are walls, so pacman can not move through it. Pacman is denoted as '@' and can move in free space.

### CODE REVIEW

**Review by smilegupta — CHANGES_REQUESTED** [review]
As per the question pacman should if we use WASD/arrow keys! But I tried all the combinations but nothing is working. Could you look into the reason

Screenshot (742)

**Comment by swetakyada** [comment]
> As per the question pacman should if we use WASD/arrow keys! But I tried all the combinations but nothing is working. Could you look into the reason
> 
> Screenshot (742)

I looked into that problem and I have made some changes. Now the pacman can be controlled with arrow keys.

**Review by smilegupta — CHANGES_REQUESTED** [review]
Screenshot (754)
When i am collide with the walls, my pacman is dying and the game is showing over and this should not happen.

**Comment by swetakyada** [comment]
Now if the pacman collides with wall, the program will not terminate. To terminate the program, you should press Esc key.

**Review by smilegupta — APPROVED** [review]

**Comment by smilegupta** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in Easy sections of the problem statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the PacMan Game Problem - Easy section in code-with-girlscript-bangalore repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Stay tuned for our upcoming Problem Statements for the Month of September. Thanks for your contribution! Happy coding😃

**Comment by girlscript-blr** [comment]
Merged to `girlscript-blr:solution` branch in PR #81

**Comment by girlscript-blr** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Pacman Game - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the new problem statements for the Month of September and try your hand at it for earning more badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
