### PR TITLE
ShoppingCartEasySolution

### PR DESCRIPTION
**Pull request by IEAbhishek**
Used python lists to store the items along with the cost. A for loop is used to print the contents of the list along with an item id which is used for the purchase. Customer data is entered with input function. The total amount including the tax is calculated by adding the actual product cost and 6 per of the product cost as tax. The bill is generated and output onto console along with the date and time using the date time library now function.
The output screenshot is also pushed along with the code.

### CODE REVIEW

**Review by yati1998 — CHANGES_REQUESTED** [review]
Please check the CONTRIBUTING.md file for the naming convention for the file. Inside solution folder you must have a folder on your name having your solution files. Also add screenshot of your solution in that folder.

**Review by yati1998 — CHANGES_REQUESTED** [review]
Please send a PR to girlscript-blr:solution branch. Kindly refer to CONTRIBUTING.md file's Create Pull Request point.

Now that you have created the PR, you can click on the Edit button beside the PR title and change the branch this PR is pointing to. Please follow the below steps.

1. Click on Edit.



2. Change the base branch from master to solution.

**Comment by IEAbhishek** [comment]
The requested changes have been made.

**Review by yati1998 — APPROVED** [review]

**Comment by yati1998** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
