### PR TITLE
solution for cart problem added

### PR DESCRIPTION
**Pull request by shraddhavp**

### CODE REVIEW

**Comment by shraddhavp** [comment]
submitted PR

**Comment by shraddhavp** [comment]
Screenshot (72)
Screenshot (73)
Added screenshots 
For this question I have used the concept of nested lists and dictionaries

**Comment by shraddhavp** [comment]
@yajushiSri @ibhanu  Please check it and  let me know the update of my PR

**Review by ibhanu — CHANGES_REQUESTED** [review]
Please send a PR to girlscript-blr:solution branch from next time. Kindly refer to CONTRIBUTING.md file's Create Pull Request point.

Please put all of your files in a folder. Not just your executing file!

And the screenshot and description for your solution should also be included in a separate document of your choice (pdf, Docx, etc,.). 

Please try to keep your description brief not just one line. It will be easier for us to review it properly!

Please use the proper naming convention of your PR title from next time too so that we can recognize the level of problem you are submitting your PR for.

Update your PR with respective changes and get back to us

**Comment by shraddhavp** [comment]
changed @ibhanu

**Comment by ibhanu** [comment]
@shraddhavp you have to create another folder inside the solution folder and add your screenshot in Docx only!. Don't add them separately as a file.
Remove unnecessary file like IPYTHON Checkpoints

**Comment by shraddhavp** [comment]
ok I changed @ibhanu

**Review by ibhanu — CHANGES_REQUESTED** [review]
@shraddhavp you have to create another folder inside the solution folder and add your screenshot in Docx only!. Don't add them separately as a file.
Remove unnecessary file like IPYTHON Checkpoints

In code you need to do the following changes:
1. Phone Number should only take an integer as input not a string!
2. Payment option should also be an option not just a string.
3. In output you are not showing total amount of tax to be paid.
4. Try to use error handles also. if a customer enter a invalid input program should ask to enter a valid option for phone number, item id, item quantity, payment option.

If have any doubt in above bugs let me know. Update your code wrt to the bug and send PR respectively.

**Comment by ibhanu** [comment]
> ok I changed @ibhanu

@shraddhavp I want you to make a folder of your name like:
 - solution
      - shraddhavp_easy_folder
           - your py file
           - your solution_decription.docx

Ok? Please Acknowledge

**Comment by shraddhavp** [comment]
ok I will do the changes

**Comment by shraddhavp** [comment]
added @ibhanu  latst changes to the code and renamed the folders

**Comment by shraddhavp** [comment]
any more changes do inform i will do it @ibhanu

**Review by ibhanu — CHANGES_REQUESTED** [review]
Following error are still there:
1. If I enter valid phone it shows the error in the last saying can't concat str with int
error
2. If I enter invalid phone number it shows the error but moves forward rather it should ask phone number again.
phone
3. If we are selecting payment options and items out of range it throws an error but you need to ask the customer again if the choice was invalid.
paymentMethod
item

Try to handle all the error try catch or any other method which you prefer to handle all the error!
The program should never break.

**Comment by shraddhavp** [comment]
@ibhanu  added the changes told please check and let me know

**Review by ibhanu — CHANGES_REQUESTED** [review]
Following are an error which still is not covered:
1. if a customer enter phone as string you are asking him again but that if he types the number wrong again it moves forward
See the ss
error
Please try to cover this kind of error in other fields also!

2. In the final bill you are just printing tax percentage but you need to print the total tax amount.
tax

Please cover all the errors and take your time!
If still want me to clear the doubt let me know!

**Comment by shraddhavp** [comment]
@ibhanu  tried best to cover the erros

**Review by ibhanu — CHANGES_REQUESTED** [review]
Update your solution doc with the latest screenshot!
This is the last change :)

**Comment by shraddhavp** [comment]
done with the latest changes and added screenshots @ibhanu

**Comment by shraddhavp** [comment]
any further updates do let me know @ibhanu

**Review by ibhanu — APPROVED** [review]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Comment by shraddhavp** [comment]
thanks @ibhanu

**Comment by shraddhavp** [comment]
@ibhanu  after how many days will i get the badge for the merged pull request?

**Comment by girlscript-blr** [comment]
Hello @shraddhavp ,

I hope you are doing well.

Yes, I checked. It was somehow missed from our side. We are extremely sorry for the inconvenience caused.

I have shared your badge now. You should have received an email from **Badgr Europe** with the subject as, **Congratulations, you earned a badge!** As such, you can download and collect your respective badges from the same.

Show the world what you have achieved through these cool badges by adding hashtags like #codeWithGirlscriptBangalore #GirlscriptBangalore and don't forget to tag us in your posts.

In case you still have not received any email from Europe Badgr or [Badgr.com](https://badgr.com) and have not received your badge, feel free to reach out to us. We'll be happy to help you out with the issue.

Check out our [Problem Statements](https://github.com/girlscript-blr/code-with-girlscript-bangalore) for the month of August if you haven't yet and add more feathers to your cap. 🤗

**Pull request merged**
