### PR TITLE
easy and medium

### PR DESCRIPTION
**Pull request by nksnny**

### CODE REVIEW

**Comment by yati1998** [comment]
Please send a PR to girlscript-blr:solution branch. Kindly refer to CONTRIBUTING.md file's Create Pull Request point.

Now that you have created the PR, you can click on the Edit button beside the PR title and change the branch this PR is pointing to. Please follow the below steps.

1. Click on Edit.



2. Change the base branch from master to solution.

**Review by yati1998 — CHANGES_REQUESTED** [review]
Please send a PR to girlscript-blr:solution branch. Kindly refer to CONTRIBUTING.md file's Create Pull Request point.

Now that you have created the PR, you can click on the Edit button beside the PR title and change the branch this PR is pointing to. Please follow the below steps.

1. Click on Edit.



2. Change the base branch from master to solution.

**Comment by nksnny** [comment]
Sorry for the Trouble , I am new to GitHub

**Comment by yati1998** [comment]
> Sorry for the Trouble , I am new to GitHub

No issues. Just check the [CONTRIBUTING.md](https://github.com/girlscript-blr/code-with-girlscript-bangalore/blob/master/CONTRIBUTING.md) file for more details

**Review by yati1998 — APPROVED** [review]

**Comment by yati1998** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `MEDIUM` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy and Medium` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out our [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem and try your hand at it to earn **THE AFICIONADO** 🥇 and **GEEK OF THE GEEKS** 🏆 badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
