### PR TITLE
Pacman game-hard solution

### PR DESCRIPTION
**Pull request by bhargavbhatiya**
I have solved pocman game hard problem. and uploded on pacmanGame_Hard branch. In this solution I have submitted required screenshorts with .cpp file.

### CODE REVIEW

**Comment by bhargavbhatiya** [comment]
I am just begginer and this is my first pull request so i don't know how to PR and all. So i have just followed documentation. But after that it shows merge blocked and review required. So can i know when will start review process or it issue with my side. Please help or suggest anything.@yati1998 @girlscript-blr

**Comment by yati1998** [comment]
@bhargavbhatiya sure, will review it and let you know

**Review by smilegupta — COMMENTED** [review]
Hey @bhargavbhatiya  

Please have a look and update the following comments 

1) When Pacman is meeting ghost, game is not ending as ghost is not willing to eat pac man
Screenshot (741)
2) When Pacman is colliding the wall he is dying, and this should not happen
Screenshot (740)
3) Apart from that ghost is moving in just a specific row and nit the entire maze

**Comment by bhargavbhatiya** [comment]
I will upload soon changed code and solution for 1st and 2nd change as you have informed in past comment.
but in 3rd mistake as you have said, but I have used rand( ) function in cpp for move randomly. there is no other option I have seen.

**Comment by bhargavbhatiya** [comment]
@smilegupta @girlscript-blr

**Review by smilegupta — APPROVED** [review]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in HARD sections of the problem statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the PacMan Game Problem - Hard section in code-with-girlscript-bangalore repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Stay tuned for our upcoming Problem Statements for the Month of September. Thanks for your contribution! Happy coding😃

**Pull request merged**
