### PR TITLE
Nandanasreeraj

### PR DESCRIPTION
**Pull request by nandanasreeraj123**
PR of solution

### CODE REVIEW

**Review by yati1998 — CHANGES_REQUESTED** [review]
Please send a PR to girlscript-blr:solution branch. Kindly refer to CONTRIBUTING.md file's Create Pull Request point.

Now that you have created the PR, you can click on the Edit button beside the PR title and change the branch this PR is pointing to. Please follow the below steps.

1. Click on Edit.



2. Change the base branch from master to solution.

**Comment by nandanasreeraj123** [comment]
done

**Review by yati1998 — CHANGES_REQUESTED** [review]
The output of your solution is not appropriate. You need to add few more details in the bill like customer name, contact, payment method, etc. 
Please check this for more details: https://github.com/girlscript-blr/code-with-girlscript-bangalore/blob/master/Medium/1.%20Shopping%20Cart%20Problem/README.md

**Comment by girlscript-blr** [comment]
Hello @nandanasreeraj123 

This is to inform you that, we will be soon closing this PR without merging if we don't get a response by tomorrow EOD.

Thanks & Regards

**Pull request closed without merging**
