### PR TITLE
Shopping cart easy

### PR DESCRIPTION
**Pull request by raniyer**

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Before merging we require you to make a few changes to make this PR up to the convention as mentioned in the [CONTRIBUTING.md](https://github.com/girlscript-blr/code-with-girlscript-bangalore/blob/master/CONTRIBUTING.md) file.

1. The codes/files should be inside a single folder following a specific naming convention. The solution folder name should be `<your GitHub Id>_<your name>`.

2. Also, you missed the `Total tax` in the billing output mentioned [here](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Easy/1.%20Shopping%20Cart%20Problem#variable-data).

3. You don't need to include the compiled version of the code, i.e. `solution.class` file, please remove it.

**Comment by raniyer** [comment]
Hey @irshadjsr21 ,
I have updated the changes, please review.

Thank you so much. :))

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
The folder with your name should be inside the `solutions` folder itself. 
For example if your folder name is `Raniyer_Nidhi-Raniyer`, then it should be inside `Easy/1. Shopping Cart Problem/solutions/Raniyer_Nidhi-Raniyer/`. Then inside that, you have to put your solutions.

**Comment by raniyer** [comment]
oh, okay.
Updated the path accordingly.  @irshadjsr21

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊🎉 on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never ending process. 📈 Check out the other versions of the problem and try your hand at it. Thanks for your contribution! Happy coding😃

**Pull request merged**
