### PR TITLE
Easy Cart problem Solution 

### PR DESCRIPTION
**Pull request by Anmolreshi**
Kindly review and add

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please read the [CONTRIBUTING.md](https://github.com/girlscript-blr/code-with-girlscript-bangalore/blob/master/CONTRIBUTING.md) file carefully.

It clearly states the naming convention for the branches.
```
Create a new branch: Follow proper naming convention before creating your own branch. The example of the naming is as follows

    Example: If you want to create a pull request in the Shopping Cart Problem - Easy, your branch name can be ShoppingCartEasy.

```

**Comment by irshadjsr21** [comment]
Hello @Anmolreshi,

This is to inform you that, you will not receive your badge if your PR is merged after **31st July 2020**.
Please update the requested change requests before 31st July.

Thanks & Regards!

**Comment by Anmolreshi** [comment]
okay
i will change the things accordingly

**Comment by Anmolreshi** [comment]
please review #61 as i added files according naming conention required for this kindly approve it and i am closing this one for time being

**Pull request closed without merging**
