### PR TITLE
Implementation of Digital Hospital Monitor Hard Solution

### PR DESCRIPTION
**Pull request by srimanikantapalakollu**
@girlscript-blr Please review my PR.!

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
You application look amazing 😍 

Just I found one **bug** in the app similar to your Medium problem's PR.
The `Discharge Date` & `Death Date` can't be before the `present date`. I am sure that can be fixed in the calendar.
Screenshot 2020-10-08 at 12 59 22 AM

**Comment by srimanikantapalakollu** [comment]
@girlscript-blr please review my PR.! I have implemented the requested changes.

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
I found few more bugs here. Please resolve them

- Under `Hospital Statistics` for Hospital Name input field. It will be better to add a **drop-down** with a **list of the hospital names** to avoid users making spelling mistakes with Hospital Names.
Screenshot 2020-10-09 at 12 28 55 AM


- Even after **discharging a Patient**. Under `Hospital Statistics` the Patient Discharge Count should increase & the Total number of Patients in Hospital should decrease by 1. But I see the values are not updating

Screenshot 2020-10-09 at 12 33 03 AM

Screenshot 2020-10-09 at 12 34 26 AM

- Also under the **Patient portal,** under `Hospital Search` the Beds Availability count should be updated after a Patient gets discharged.
Screenshot 2020-10-09 at 12 35 05 AM

**Comment by srimanikantapalakollu** [comment]
@girlscript-blr implemented the requested changes. please review my PR.!

**Review by girlscript-blr — APPROVED** [review]

**Comment by girlscript-blr** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in the `Advanced` sections of the Problem Statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **Digital Hospital Manager** - Hard section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Also [RSVP here](https://tinyurl.com/gsblr-hacktoberfest2020) to win\* a limited edition **Hacktoberfest** 👕Tee-shirt or a 🎍plant if you haven't yet.

Learning is a never-ending process. 📈 Check out the [Bonus](https://github.com/girlscript-blr/code-with-girlscript-bangalore/blob/master/Bonus/4.%20Digital%20Hospital%20Manager/README.md) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
