### PR TITLE
Shopping cart hard

### PR DESCRIPTION
**Pull request by damini31**

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please implement the following Changes:
- Remove the easy solution file from this PR as it is giving merge conflicts.
`Easy/1. Shopping Cart Problem/solutions/damini31_DaminiChauhan/ShoppingCart_Easy.cpp`

- While adding a new product in the Category, I bymistake gave item number in place of Category Id, but instead of not allowing me or displaying a message to retry, it allowed me to  enter and accepted it.
Screenshot 2020-07-26 at 12 40 45 PM

- While creating a new Category, I by mistake pressed enter. It should have given a retry message in place of accepting.
Screenshot 2020-07-26 at 12 42 41 PM

- When I select `View all shopping categories and filter & sort them with name` I don't see the list of Shopping Categories getting displayed.
Screenshot 2020-07-26 at 1 04 23 PM


- When I select sort the order, it is displaying wrong message
Screenshot 2020-07-26 at 12 46 38 PM

- In vendor mode when I try to update order status, I should be provided with the 3 options on what to update, the user won't be knowing what are the input options, he/she might try to enter anything and that will break the code.
Screenshot 2020-07-26 at 12 48 49 PM

- When a customer creates a new order, the Order Id should be mention in the bill, so that he/she can check his/her order status by providing the Order Id. I don't see the Order Id in the bill.
Screenshot 2020-07-26 at 12 53 01 PM

**Comment by damini31** [comment]
Hi,
I have implemented the changes in the code as requested,
I have also deleted  ShoppingCart_Easy.cpp.
Kindly let me know in case anything else is needed.
Thank you! :D

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
I can still see the easy folder files, because of which it is giving merge conflicts.
I guess you need not add these easy folder files while sending the PR or keep the easy folder files exactly same as merged in our `girlscript-blr:solution` branch.

Screenshot 2020-07-27 at 12 56 30 PM

**Comment by damini31** [comment]
Hi,
I have deleted the folder from my end but I can still see that there are conflicts.
I think you might delete it from your end as you do have write access to this repository whereas I do not, if that's not a problem.

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Deleting from our end doesn't seem to be possible, these files are deleted after forking.
And if I try to merge the PR the Easy folder in `girlscript-blr:solution` branch will get deleted, which we cannot.
There are 2 approaches to resolve this conflict
- You can take a new fork from `girlscript-blr:master` branch, copy-paste your named folder i.e. `damini31_DaminiChauhan` along with your Hard solution files inside the `Hard/1. Shopping Cart Problem/solutions/` and send a new PR.
- You can add the Easy folder back into your `ShoppingCartHard` branch and make it exactly the same as in our `girlscript-blr:master` branch.

You can try any of the approaches. if you get stuck or need our help feel free to let us know, we will be happy to help.

Also there are few issues in the code:
- When I try to sort customer order as per billing date, I am getting the following error
Screenshot 2020-07-29 at 12 13 03 AM

- These Product Ids being in float can confuse the user to enter **.0** which breaks the code.
Screenshot 2020-07-29 at 12 14 34 AM

- When I tried to filter the order based on Total Amount, it didn't give the expected results.
Screenshot 2020-07-29 at 12 26 21 AM

**Comment by damini31** [comment]
Hi,
I have sent a new pull request. Kindly see to it and let me know in case anything else is required.
Thank you!

**Comment by girlscript-blr** [comment]
A new PR [#65](https://github.com/girlscript-blr/code-with-girlscript-bangalore/pull/65) is created by the participant to resolve merge conflicts. Hence closing this PR.

**Pull request closed without merging**
