### PR TITLE
Added Solution to Shopping cart intermediate

### PR DESCRIPTION
**Pull request by Vanshikaa00**
Hey... I've added solution to Shopping Cart Intermediate problem in java in : Medium > Shopping Cart Problem > solutions > Vanshikaa00_Vanshika folder. Thanks ! :smile:

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please output the `Total amount saved` as mentioned in the question.

**Comment by irshadjsr21** [comment]
Also, I noticed you haven't filled [this form](https://tinyurl.com/codewithgsblr) mentioned on the `README.md` file.

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
The total amount saved is not correctly calculated. This is how it should be calculated.
Suppose I buy a pen which has a price of Rs. 10, and being sold at a discount price of Rs. 8. If I buy 2 pens, then I save Rs. 4.
image

**Comment by Vanshikaa00** [comment]
Hey @irshadjsr21 ! I've updated the solution. Previously, i think i misunderstood about total amount saved 😅 so thanks for pointing the error that i had in the previous commit . Let me know if it's correct now or not . Also, i've filled out the participation form now. ✌️

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
The 1st image shows the item and it's discount price but after billing, I'm not getting the discount. 
image
image

**Comment by Vanshikaa00** [comment]
Actually i'm giving discount only when user enters a large quantity of the product ; like in the above images you're entering the quantity of earphones less than 3 so you're being charged with original price, if their quantity was more than 3 then you would've been charged with discounted price and so in the bill i'm displaying that and same goes for all other items. So, that's why you're getting discount on certain items and not on other items .Also, in bill if you are getting discount then it is being displayed else original price is displayed. Hence amount saved , tax and total sum to pay are calculated based on that

**Comment by irshadjsr21** [comment]
It's good that you're providing this feature, but please mention it while printing the items and also in the document.

**Comment by Vanshikaa00** [comment]
okay i'll be careful so.. do i need to change it and give discount on all items irrespective of their quantity?

**Comment by irshadjsr21** [comment]
No, just mention which item has how much discount on buying how many of them.

**Comment by Vanshikaa00** [comment]
@irshadjsr21 I've made the changes

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `MEDIUM` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Medium` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out our [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem and try your hand at it to earn **THE AFICIONADO** 🥇 and **GEEK OF THE GEEKS** 🏆 badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
