### PR TITLE
Solution for Shopping Cart Medium

### PR DESCRIPTION
**Pull request by encarcio**

### CODE REVIEW

**Comment by ibhanu** [comment]
Following bugs are found, please look into it:
1. Using n {small 'n'} in when it asks for more items. It still asks for more items to be entered. but rather it should move forward.
2. When selecting same item again it should check if the item is already existing in the cart or not. Now it just replaces the item quantity with new item's quantity.
3. When entering the name it takes the first name as name and last name as phone no.
4. In the total bill, it does not show discounted price for individual items.
5. In the total bill its not showing shipping prize too.

Please look into this push the updated code.

**Review by ibhanu — CHANGES_REQUESTED** [review]
Following bugs are found, please look into it:
1. Using n {small 'n'} in when it asks for more items. It still asks for more items to be entered. but rather it should move forward.
2. When selecting same item again it should check if the item is already existing in the cart or not. Now it just replaces the item quantity with new item's quantity.
3. When entering the name it takes the first name as name and last name as phone no.
4. In the total bill, it does not show discounted price for individual items.
5. In the total bill its not showing shipping prize too.

Please look into this push the updated code.

**Comment by encarcio** [comment]
I have done all the changes which you have pointed in the code review.Please check the updated code again.

**Review by ibhanu — CHANGES_REQUESTED** [review]
Please do the following changes wrt the new code you committed:

1. If a customer tries to enter an invalid option of item. It does not handle the exception which shows at the end of the program. screen attached for reference
addr

2.  Phone number should only accept integer value not a string/var
phoneNumber

3. There is some exception when choosing delivery method
ss_takeaway

4. Please round of tax to 2 points after the decimal.
taxRound

5. And Billing date and time should be displayed in a single line.

**Comment by encarcio** [comment]
I have fixed the bugs which you have mentioned. Please review the updated code.

**Review by ibhanu — CHANGES_REQUESTED** [review]
I still don't see round off in tax output!
And update your pdf accordingly, please!

**Comment by encarcio** [comment]
Rounded the tax and updated the pdf accordingly. Please review the changes

**Review by ibhanu — APPROVED** [review]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `MEDIUM` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy and Medium` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out our [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem and try your hand at it to earn **THE AFICIONADO** 🥇 and **GEEK OF THE GEEKS** 🏆 badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
