### PR TITLE
Shopping cart problem   easy,

### PR DESCRIPTION
**Pull request by AcidBurn18**

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please implement the following steps as change requests:
- Display the **item list** as suggested in the question, as the user won't know which product to buy as no items with price tags are getting displayed. Attached screenshot for reference.
Screenshot 2020-07-07 at 10 19 05 PM

- While submitting please remove **extra readme.md file and .py file** present outside your folder. Please don't check-in anything other than your folder containing the document and solution file.
- Rename your folder to `AcidBurn18_AnshAgrawal` from `<AcidBurn18>_<Ansh Agrawal>`
- Also, provide a technical description for the approach taken to implement this problem in the document/readme.md file present inside your folder.

**Review by AcidBurn18 — COMMENTED** [review]
All the requested changed have been worked on

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Your code seems to work fine but, it will be better if you make the user select numbers in place of typing word. Chances of spelling mistakes increase when a user types the product/item name. Refer screenshot:
Screenshot 2020-07-08 at 10 03 15 PM

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
You have deleted the [README.md](https://github.com/girlscript-blr/code-with-girlscript-bangalore/blob/master/Easy/1.%20Shopping%20Cart%20Problem/solutions/README.md) file which was present under solution folder. Because of this, it is giving merge conflicts. Kindly add it back as it was.

**Comment by AcidBurn18** [comment]
Have been taken care of

**Review by girlscript-blr — APPROVED** [review]

**Comment by girlscript-blr** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problems and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
