### PR TITLE
Shopping cart easy

### PR DESCRIPTION
**Pull request by Abhijit2505**
Have a look, I have made the required changes.

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
You can remove one of the `.md` or `.pdf` documentation, only one of them is required.
Also, you don't need to close the PR to make changes to it. You can just push the new changes to the branch the PR was made from and the PR will be updated automatically.

**Comment by Abhijit2505** [comment]
> You can remove one of the `.md` or `.pdf` documentation, only one of them is required.
> Also, you don't need to close the PR to make changes to it. You can just push the new changes to the branch the PR was made from and the PR will be updated automatically.

Is there any problem if both the .md and .pdf file remains?

Also, kindly merge the PRs when the solution is correct and you get the required info out.

**Comment by irshadjsr21** [comment]
Keeping both will just increase the repo size needlessly. Please remove one to make this PR mergeable.

**Comment by Abhijit2505** [comment]
Ok Great.

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Now that the `.md` is removed, the `.png` file is no longer required. Please remove that also.

**Comment by Abhijit2505** [comment]
Have a look now.

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) of the problem and try your hand at it for earning higher level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
