### PR TITLE
Submission of Medium/1. Shopping Cart Problem/

### PR DESCRIPTION
**Pull request by chttrjeankr**
Application created to let user shop for multiple items of valid quantity with applicable discounts and 6% tax.
User is allowed to opt for home delivery for under 50 km distance from the shop.

@irshadjsr21 @girlscript-blr

### CODE REVIEW

**Review by irshadjsr21 — COMMENTED** [review]
Good work!

Below are some tips/improvements that can be made in the application. These changes are completely optional, and you may choose not to make these changes. 

**Just a few tips**
1. All the `API` routes should be in a separate `/api` path, to maintain consistency and prevent any confusion with template paths.
2. Display add to cart button initially and when the item is added to the cart, show the quantity change input.
image
3. Currently when you go to the shopping list page, add some item, click checkout, and click continue shopping, your selections won't be displayed on the shopping list page.
4. Currently, I can enter my name in the phone no field. This can easily be fixed with input type and pattern attribute. 
image
5. The date and time can be made more user friendly.
image

**You have 2 options as of now:**
1. Comment on this PR that you want to merge it and I'll do the same because this solution has already fulfilled the medium problem criteria.
2. Make the appropriate changes, push the code & request for review.

**P.S.**: I have given you these options because I think you have the potential to do better.

**Comment by chttrjeankr** [comment]
The suggestions are awesome and I'm really happy you took the time to review it so minutely! :smile:

**Comment by chttrjeankr** [comment]
The suggestions are awesome and I'm really happy you took the time to review it so minutely. :smile: 

<hr>

> All the `API` routes should be in a separate `/api` path, to maintain consistency and prevent any confusion with template paths.

I think you are suggesting a different folder for the routes. My current tree is as follows:
```
.
├── app.py
├── README.md
├── requirements.txt
├── static
│   └── js
│       └── logic.js
├── templates
│   ├── base.html
│   ├── create_order.html
│   ├── display_bill.html
│   ├── index.html
│   └── shopping_list.html
└── utilities.py
```
I think I understand your point but could you help me by suggesting how the tree should be? And what exactly do you think should be moved into the new folder?

<hr>

> * Display add to cart button initially and when the item is added to the cart, show the quantity change input.
>   image
> * Currently when you go to the shopping list page, add some item, click checkout, and click continue shopping, your selections won't be displayed on the shopping list page.

TBH, I did try having this so that the latest quantity is shown in the `shopping_list` page but it all turned out to be far too complicated with my implementation of `cart` and `shopping_list` and I thought I'll just let it be. But since you pointed this out, I'm willing to make this change when I submit the Hard part of this problem statement. The temporary `cart` variable I use is not a very good choice (I realized later) as it's not searchable by only the item name. But changing it after I realized it, would've meant changing a LOT of things. And I wasn't prepared for that. This will SURELY be included in the Hard solution. :100: I'll mention your comment in my Hard PR too, for reference.

<hr>

> * Currently, I can enter my name in the phone no field. This can easily be fixed with input type and pattern attribute.
>   image
> * The date and time can be made more user friendly.
>   image

YES. I missed paying attention to these. :disappointed: Would it be fine if I took these points too to the Hard solution? I've currently started working on that keeping the Medium solution as a base and I'm already improving things there. I'm a bit hesitant to change this PR for the same reason.

<hr>

> I have given you these options because I think you have the potential to do better.

Thanks a LOT for believing. :star2: @irshadjsr21 
I'd make sure to include all these changes in the Hard solution I'm working on. So if that's okay, I'd like to see this one merged and completed.

**P.S.:** I need a bit of help to understand how to implement your point 1.

**Comment by irshadjsr21** [comment]
> I think I understand your point but could you help me by suggesting how the tree should be? And what exactly do you think should be moved into the new folder?

You don't necessarily have to change the folder structure. Just all the `API` routes should be a sub route of `/api`. For example, in the app, you have a `/add_to_cart` route, you can change this to `/api/add_to_cart`. Similarly, if you have any other `API` route you can do the same with it.

If you want to go a step further and improve the application architecture by splitting routes into different files, refer [this article](https://aligoren.com/how-i-structure-my-flask-apps/). And to learn more in detail, refer [this](https://exploreflask.com/en/latest/index.html).

One more thing. Don't take a pull from the `solution` branch. You have to take the pull from `master` and make a PR to `solution`. I can see other people's solutions in your branch. We made the `solution` branch so that your codebase won't get polluted with other people's solutions. Keep this in mind.

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `MEDIUM` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Medium` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out our [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem and try your hand at it to earn **THE AFICIONADO** 🥇 and **GEEK OF THE GEEKS** 🏆 badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
