### PR TITLE
Add Medium Solution

### PR DESCRIPTION
**Pull request by AnjaliPatle**

### CODE REVIEW

**Review by girlscript-blr — CHANGES_REQUESTED** [review]
Please resolve the following issues:

- Send PR to our `girlscript-blr: solution` branch in place of `girlscript-blr: master` branch. You can modify that in github itself, clicking the edit button on the top right corner as shown in the screenshot
Screenshot 2020-10-31 at 1 46 06 PM

- When I **Add a Patient**, after `successfully submitting` I see the following fields don't get reset. I guess you can reassign the values to null after the Add Patient operation is complete.
Screenshot 2020-10-31 at 1 43 08 PM

- When I try to **Update a Patient Detail**, I am able to select a calendar dates for Discharge/Deceased **before the admission date**, which is logically not correct. Either you can disable the calendar to select a date after the admission date, or while submitting you can show an error msg stating, Patient cannot be updated as the date entered is wrong.
Screenshot 2020-10-31 at 1 40 26 PM

- There needs to be another calendar date if deceased. There can be a possibility that a Patient is deceased on a certain date-time & discharged on another date. Also remember to not all deceased date to be before the date of admission.
Screenshot 2020-10-31 at 1 44 49 PM

**Please try to resolve these change requests by today itself to have an opportunity to receive goodies from HACKTOBERFEST2020. We can still share your badge with you in November as well, but we don't think Hacktoberfest ppl will accept the PR after 31st October.**

**Comment by girlscript-blr** [comment]
Hello @AnjaliPatle 

Please resolve the change requests before 10th November, 2020 to receive your badge.

Thanks & Regards

**Comment by AnjaliPatle** [comment]
Hey, I've made the suggested changes. Thank you for your time and review and I'm really sorry for the delay. Please let me know  if you'd like any other changes.

**Review by girlscript-blr — APPROVED** [review]

**Comment by girlscript-blr** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in the `Medium` sections of the Problem Statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **Digital Hospital Manager - Medium** section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out our **November Month's** [Easy](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Easy/5.%20IPL%20Management%20App), [Medium](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/5.%20IPL%20Management%20App)  and [Hard](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/5.%20IPL%20Management%20App) level problem statements and try your hand at it for earning this month's badges. 

Thanks for your contribution! 
Happy coding😃

**Pull request merged**
