### PR TITLE
Shopping cart easy

### PR DESCRIPTION
**Pull request by bagofcodes**
Solution for the problem Shopping Cart(Easy)

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please include all the project dependencies in a `requirements.txt` file so that it can be installed directly from pip.

**Comment by bagofcodes** [comment]
There are no extra dependancies that needs to be installed for this program. tkinter module comes pre installed with python

**Comment by bagofcodes** [comment]
No extra dependancies needs to be added. Tkinter comes installed with
python only. Please review.Thanks & Regards

**Comment by irshadjsr21** [comment]
Maybe it's not installed on all OS.
image

**Comment by bagofcodes** [comment]
Ok i will add it. Give me some time.

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Remove the `requirements.txt` on the root location. 

Also please provide the dependency version in the `requirements.txt`, otherwise, it's throwing an error.
image

**Comment by bagofcodes** [comment]
please check it once this time. Actually it comes pre-installed with python 3 so I  was having a hard time finding the correct way to install that. But I think this time it should work fine

**Comment by bagofcodes** [comment]
Please review the changes....

**Comment by bagofcodes** [comment]
Screenshot (63)

Please see this ss. Python comes installed with the Tkinter module. if You are having any problems. Please refer to below links
[link1](https://stackoverflow.com/questions/25905540/importerror-no-module-named-tkinter)
[link2](https://tkdocs.com/tutorial/install.html)

**Review by girlscript-blr — APPROVED** [review]
Able to run the code in sypder.

**Comment by bagofcodes** [comment]
do the requested changes still needs to be addressed as the pull request is yet not merged??

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Only one of the `README.md` or `pdf` is enough. Please remove the `README.md` and other `gif` files and keep only the `pdf`.

Also, remove the `requirements.txt` file.

**Comment by bagofcodes** [comment]
Necessary changes are addressed...Please review

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃
Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
