### PR TITLE
Digital Hospital Manager Easy

### PR DESCRIPTION
**Pull request by srimanikantapalakollu**
Developed the Python-based CLI Application for the problem statement.

### CODE REVIEW

**Review by ibhanu — CHANGES_REQUESTED** [review]
To the following changes to the code and you are good to go.
1. Change the data type of contact number.
2. Change the data type of emergency contact number.

**Comment by srimanikantapalakollu** [comment]
Where should I need to change the Data type? is it in Python input or in the DB file?

**Comment by srimanikantapalakollu** [comment]
@ibhanu please let me know.

**Comment by ibhanu** [comment]
Both! Because phone number are Integers

**Comment by srimanikantapalakollu** [comment]
@ibhanu If we set tp integer, there might be an issue with storing the country code eg: +91, +1, +44, etc. and also in sqlite3, this might cause an integer overflow problems. So to avoid those issues I have used the String data type.

**Review by ibhanu — APPROVED** [review]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull request made in `Easy` sections of the Problem Statement.

Congratulations🎊 🎉 on getting your pull request successfully merged in the **Digital Hospital Manager** - Easy section in **code-with-girlscript-bangalore** repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Try your hand at it for earning higher-level badges. 

Also [RSVP here](https://tinyurl.com/gsblr-hacktoberfest2020) to win\* a limited edition **Hacktoberfest** 👕Tee-shirt or a 🎍plant.

Thanks for your contribution! Happy coding😃

**Pull request merged**
