### PR TITLE
PACMAN GAME

### PR DESCRIPTION
**Pull request by sujal111**
Python PACMAN GAME

### CODE REVIEW

**Comment by chttrjeankr** [comment]
> * It goes without saying that plagiarism is strictly discouraged. Kindly refrain from the urge to do it.

_From https://github.com/girlscript-blr/code-with-girlscript-bangalore#general-guidelines_

Original repository: https://github.com/a-plus-coding/pacman-with-python
@girlscript-blr

**Comment by girlscript-blr** [comment]
> > * It goes without saying that plagiarism is strictly discouraged. Kindly refrain from the urge to do it.
> 
> _From https://github.com/girlscript-blr/code-with-girlscript-bangalore#general-guidelines_
> 
> Original repository: https://github.com/a-plus-coding/pacman-with-python
> @girlscript-blr

Thank you @chttrjeankr , we really appreciate your concern.

**Comment by girlscript-blr** [comment]
Hello @sujal111 

We have received your submission and on verifying, it is noticed that your code is exactly same as : https://github.com/a-plus-coding/pacman-with-python 

**It seems to be copied.**  

We want to bring to your note once again that plagiarism is strictly discouraged and hence **we are rejecting this PR and closing without merging**. 

If you want to continue, you can send a new PR with your own code and a new logic.

Please refrain from any plagiarism behind practiced. If we find such incidents in the future, we regret to mention but we will have to debar you from this Code with Girlscript Bangalore Program. We hope you understand the concern here.

**Comment by sujal111** [comment]
Extremely sorry for the same.
I thought since it's a beginner level stuff, I can modify and submit.
Won't repeat again.

**Pull request closed without merging**
