### PR TITLE
Shopping Cart Easy

### PR DESCRIPTION
**Pull request by Harshitha-sa**
I have used C++ for solving the problem.
*(Array of Objects to store the items and their prices.)

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please send a PR to `girlscript-blr:solution` branch. Kindly refer to [CONTRIBUTING.md](https://github.com/girlscript-blr/code-with-girlscript-bangalore/blob/master/CONTRIBUTING.md) file's Create Pull Request point.

Now that you have created the PR, you can click on the `Edit` button beside the PR title and change the branch this PR is pointing to. Please follow the below steps.

1. Click on `Edit`.
image

2. Change the base branch from `master` to `solution`.
image

**Comment by Harshitha-sa** [comment]
👍,I have changed it @irshadjsr21

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
You don't need to include the compiled version of the code. Please remove the `.exe` file and this PR is good to go.

**Comment by Harshitha-sa** [comment]
Removed .exe file @irshadjsr21

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊🎉 on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in code-with-girlscript-bangalore repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never ending process. 📈 Check out the other versions of the problem and try your hand at it. Thanks for your contribution! Happy coding😃

**Pull request merged**
