### PR TITLE
Shopping cart easy

### PR DESCRIPTION
**Pull request by encarcio**

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please remove the compiled files (i.e. all the `.class` files).

**Tip**
Whenever you create an application where the user is allowed to select an item, don't make the user type its name. Because the user might make a mistake and your app can crash. Another reason is you'll have do a search operation to find the item the user has typed. To avoid this ask the user to just enter the index of the item in that list (like 1, 2, 3, etc).

Here's how your app responds when the user makes a mistake in typing the name of the item.
image

**Comment by encarcio** [comment]
Thank you for such a good advice. I have done all the changes which you have pointed in the code review

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
There seems to be a bug in your code. Here, I clearly selected the Compute Monitor but the bill was generated for Smart watch.

image

**Comment by encarcio** [comment]
Fixed the menu printing order bug in which proper index was not assigned to each item

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
