### PR TITLE
Shopping cart easy solution added.

### PR DESCRIPTION
**Pull request by garimasingh128**

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
1. There seems to be a bug in your code, the total tax was 0 on the purchase of 6000.
image

2. Also. a brief description(not more than 4-5 lines/100 words) needs to be included containing the approach used for solving the problem along with the screenshot in a pdf document format.

**Comment by garimasingh128** [comment]
Updated!

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Everything looks good, just remove the compiled version of the solution (i.e., `.exe` file).

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Comment by garimasingh128** [comment]
Done!

**Pull request merged**
