### PR TITLE
Submission of Easy/1. Shopping Cart Problem/

### PR DESCRIPTION
**Pull request by chttrjeankr**
Application created to let user shop for a _specific_ item of valid quantity with _no discounts_ and 6% tax.

@irshadjsr21 @girlscript-blr

### CODE REVIEW

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
1. It's good that you have mentioned the steps to run the project in the `Readme` file. But please include a  brief description(not more than 4-5 lines/100 words) containing the approach used for solving the problem along with the screenshot in a separate `pdf` document.

2. Currently, the shopping list & the generated bill is just a `JSON` object, whereas the create order page is an `HTML` template. Try to keep all the UI in the same format (i.e. Use HTML templates for all the user interface)

**Comment by chttrjeankr** [comment]
> 1. It's good that you have mentioned the steps to run the project in the `Readme` file. But please include a  brief description(not more than 4-5 lines/100 words) containing the approach used for solving the problem along with the screenshot in a separate `pdf` document.

I have already added a section titled Approach with 4 bullet points in the `README.md` and used GIFs for simulation in place of screenshots for the explanation, in a markdown document format, just like it was mentioned in the project guidelines:

> A brief description(not more than 4-5 lines/100 words) should be included containing the approach used for solving the problem. - Make this submission in a document format, containing both description and simulation/output screenshot(s).

@irshadjsr21, Could you verify if by document format you mean only `PDF`s and if only screenshots are allowed and not simulations?

**Comment by chttrjeankr** [comment]
> 2\. Currently, the shopping list & the generated bill is just a `JSON` object, whereas the create order page is an `HTML` template. Try to keep all the UI in the same format (i.e. Use HTML templates for all the user interface)

Great point. Going to create new commits regarding this pretty soon. Thanks. :smile: 

Would you mind making it clear [here](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Easy/1.%20Shopping%20Cart%20Problem#output). I was under the impression that the `bill can be in any format`.
> Output will be a bill based on the given input. The bill can be in any format but it must include the following

**Comment by irshadjsr21** [comment]
> Would you mind making it clear [here](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Easy/1.%20Shopping%20Cart%20Problem#output). I was under the impression that the `bill can be in any format`.
> 
> > Output will be a bill based on the given input. The bill can be in any format but it must include the following

Yes, You can give the output in any format but it is good to be consistent in the approach you are using. Since you were using HTML templates, it'll be good to have all the input/output in that format.

**Comment by irshadjsr21** [comment]
@chttrjeankr I just confirmed with the team and we decided to accept the document in any format. So now you don't need to create the PDF, the readme is fine.

**Review by irshadjsr21 — CHANGES_REQUESTED** [review]
Please change the shopping list UI from `JSON` to the HTML template. Or you can just remove it since the list is provided as a dropdown in the create order page. It's up to you.

If you decide to keep the shopping list page, you'll have to make it in the same format as other pages.

Also, please modify the Readme according to the new changes.

**Review by irshadjsr21 — APPROVED** [review]

**Comment by irshadjsr21** [comment]
Greetings from Code With Girlscript Bangalore😃

Dear participant, we have gone through your pull requests made in `EASY` sections of the problem statement.

Congratulations🎊 🎉  on getting your pull request successfully merged in the `Shopping Cart Problem - Easy` section in `code-with-girlscript-bangalore` repository. We will be distributing your valuable badges🥇🥈🥉🎖️ corresponding to the pull requests that are merged.

Learning is a never-ending process. 📈 Check out the [Intermediate](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Medium/1.%20Shopping%20Cart%20Problem) & [Advanced](https://github.com/girlscript-blr/code-with-girlscript-bangalore/tree/master/Hard/1.%20Shopping%20Cart%20Problem) level problem statements and try your hand at it for earning higher-level badges. Thanks for your contribution! Happy coding😃

**Pull request merged**
